const { contextBridge, ipcRenderer } = require('electron')
// Wrap invoke agar error IPC tidak throw DOMException ke renderer
// Selalu return { ok: false, error: msg } jika IPC gagal
const invoke = async (ch, ...a) => {
  try {
    return await ipcRenderer.invoke(ch, ...a)
  } catch (e) {
    // IPC error (structured clone, handler crash, dll) - kembalikan plain error object
    return { ok: false, error: String(e && e.message ? e.message : e), _ipc_error: true }
  }
}

contextBridge.exposeInMainWorld('api', {
  auth:     { login: (e,p) => invoke('auth:login',e,p) },
  sekolah:  {
    get:         ()      => invoke('sekolah:get'),
    save:        d       => invoke('sekolah:save', d),
    uploadLogo:  field   => invoke('sekolah:upload_logo', field),
    removeLogo:  field   => invoke('sekolah:remove_logo', field),
    uploadKop:   ()      => invoke('sekolah:upload_kop'),
    hapusKop:    ()      => invoke('sekolah:hapus_kop'),
    uploadTtd:   ()      => invoke('sekolah:upload_ttd'),
    hapusTtd:    ()      => invoke('sekolah:hapus_ttd'),
  },
  semester: {
    list:    ()        => invoke('semester:list'),
    add:     d         => invoke('semester:add',d),
    update:  (id,d)    => invoke('semester:update',id,d),
    delete:  id        => invoke('semester:delete',id),
    reorder: ids       => invoke('semester:reorder',ids),
  },
  siswa: {
    list:            q       => invoke('siswa:list',q),
    get:             id      => invoke('siswa:get',id),
    add:             d       => invoke('siswa:add',d),
    update:          (id,d)  => invoke('siswa:update',id,d),
    delete:          id      => invoke('siswa:delete',id),
    generateNoSkl:   opts    => invoke('siswa:generate_no_skl', opts),
    updateNoSkl:     (id,v)  => invoke('siswa:update_no_skl', id, v),
    uploadFoto:      id      => invoke('siswa:upload_foto', id),
    removeFoto:      id      => invoke('siswa:remove_foto', id),
    importExcel:     ()      => invoke('siswa:import_excel'),
    downloadTemplate:()      => invoke('siswa:download_template'),
    stats:           ()      => invoke('siswa:stats'),
  },
  mapel: {
    list:        ()     => invoke('mapel:list'),
    add:         d      => invoke('mapel:add',d),
    update:      (id,d) => invoke('mapel:update',id,d),
    delete:      id     => invoke('mapel:delete',id),
    reorder:     ids    => invoke('mapel:reorder',ids),
    seedDefault: ()     => invoke('mapel:seed_default'),
  },
  nilai: {
    getSiswa:       id   => invoke('nilai:get_siswa',id),
    saveBatch:      rows => invoke('nilai:save_batch',rows),
    rekap:          ()   => invoke('nilai:rekap'),
    ranking:        (angkatan_id) => invoke('nilai:ranking', angkatan_id ?? null),
    rekapSiswa:     id   => invoke('nilai:rekap_siswa',id),
    rekapAngkatan:  id   => invoke('nilai:rekap_angkatan',id),
    importTemplate: ()   => invoke('nilai:import_template'),
    importNilai:    ()   => invoke('nilai:import_nilai'),
  },
  angkatan: {
    list:        ()       => invoke('angkatan:list'),
    add:         d        => invoke('angkatan:add',d),
    update:      (id,d)   => invoke('angkatan:update',id,d),
    delete:      id       => invoke('angkatan:delete',id),
    getSiswa:    id       => invoke('angkatan:siswa',id),
    tambahSiswa: (id,ids) => invoke('angkatan:tambah_siswa',id,ids),
    hapusSiswa:  (id,ids) => invoke('angkatan:hapus_siswa',id,ids),
  },
  nomorSurat: {
    getAll:  ()           => invoke('nomor_surat:get_all'),
    save:    (field, val) => invoke('nomor_surat:save', field, val),
    saveAll: data         => invoke('nomor_surat:save_all', data),
  },
  export: {
    excelAngkatan: (id)        => invoke('export:excel_angkatan', id ?? null),
    excelSiswa:    siswa_id    => invoke('export:excel_siswa', siswa_id),
    excelRekap:    ()          => invoke('export:excel_rekap'),
    excelRanking:  ()          => invoke('export:excel_ranking'),
  },
  pdf: {
    skl:             angkatan_id => invoke('pdf:skl', angkatan_id),
    dkn:             angkatan_id => invoke('pdf:dkn', angkatan_id),
    nilaiIjazah:     angkatan_id => invoke('pdf:nilai_ijazah', angkatan_id),
    ijazah:          angkatan_id => invoke('pdf:ijazah', angkatan_id),
    transkrip:       angkatan_id => invoke('pdf:transkrip', angkatan_id),
    skKelulusan:     angkatan_id => invoke('pdf:sk_kelulusan', angkatan_id),
    skkb:            angkatan_id => invoke('pdf:skkb', angkatan_id),
    // Per siswa
    sklSiswa:         id => invoke('pdf:skl_siswa', id),
    transkripSiswa:   id => invoke('pdf:transkrip_siswa', id),
    nilaiIjazahSiswa: id => invoke('pdf:nilai_ijazah_siswa', id),
    ijazahSiswa:      id => invoke('pdf:ijazah_siswa', id),
    skkbSiswa:        id => invoke('pdf:skkb_siswa', id),
  },
  kleper: {
    list:     q      => invoke('kleper:list', q),
    byHuruf:  huruf  => invoke('kleper:by_huruf', huruf),
  },
  guru: {
    list:       q      => invoke('guru:list', q),
    get:        id     => invoke('guru:get', id),
    add:        d      => invoke('guru:add', d),
    update:     (id,d) => invoke('guru:update', id, d),
    delete:     id     => invoke('guru:delete', id),
    uploadFoto: id     => invoke('guru:upload_foto', id),
  },
  absensiGuru: {
    get:   tanggal        => invoke('absensi_guru:get', tanggal),
    save:  (tanggal,rows) => invoke('absensi_guru:save', tanggal, rows),
    rekap: bulan          => invoke('absensi_guru:rekap', bulan),
  },
  jamMengajar: {
    list:   ta     => invoke('jam_mengajar:list', ta),
    save:   d      => invoke('jam_mengajar:save', d),
    delete: id     => invoke('jam_mengajar:delete', id),
  },
  skTugas: {
    list:   ()  => invoke('sk_tugas:list'),
    save:   d   => invoke('sk_tugas:save', d),
    delete: id  => invoke('sk_tugas:delete', id),
  },
  raport: {
    periodeList:   ()            => invoke('raport:periode_list'),
    periodeAdd:    d             => invoke('raport:periode_add', d),
    periodeUpdate: (id,d)        => invoke('raport:periode_update', id, d),
    periodeDelete: id            => invoke('raport:periode_delete', id),
    mapelList:     periode_id    => invoke('raport:mapel_list', periode_id),
    mapelSave:     d             => invoke('raport:mapel_save', d),
    mapelDelete:   id            => invoke('raport:mapel_delete', id),
    siswaList:     periode_id    => invoke('raport:siswa_list', periode_id),
    siswaSave:     (pid,sid,d)   => invoke('raport:siswa_save', pid, sid, d),
    nilaiGet:      (pid,sid)     => invoke('raport:nilai_get', pid, sid),
    nilaiSave:     (pid,sid,mid,d) => invoke('raport:nilai_save', pid, sid, mid, d),
    nilaiBulk:     (pid,mid,rows)  => invoke('raport:nilai_bulk', pid, mid, rows),
    rekap:         pid           => invoke('raport:rekap', pid),
    exportExcel:   pid           => invoke('raport:export_excel', pid),
  },
  peserta: {
    list:     config_id          => invoke('peserta:list', config_id),
    saveBulk: (config_id, rows)  => invoke('peserta:save_bulk', config_id, rows),
    autoNo:   config_id          => invoke('peserta:auto_no', config_id),
  },
  kartuUjian: {
    list:      ()                   => invoke('kartu_ujian:list'),
    add:       d                    => invoke('kartu_ujian:add', d),
    update:    (id,d)               => invoke('kartu_ujian:update', id, d),
    delete:    id                   => invoke('kartu_ujian:delete', id),
    getSiswa:  (cfg_id, kelas_id)   => invoke('kartu_ujian:get_siswa', cfg_id, kelas_id),
  },
  bos: {
    list:    (tahun, sem) => invoke('bos:list', tahun, sem),
    save:    d            => invoke('bos:save', d),
    delete:  id           => invoke('bos:delete', id),
    summary: (tahun, sem) => invoke('bos:summary', tahun, sem),
  },
  ppdb: {
    list:           (q, status) => invoke('ppdb:list', q, status),
    add:            d           => invoke('ppdb:add', d),
    update:         (id,d)      => invoke('ppdb:update', id, d),
    delete:         id          => invoke('ppdb:delete', id),
    updateStatus:   (id,status) => invoke('ppdb:update_status', id, status),
    terimaJadiSiswa: id         => invoke('ppdb:terima_jadi_siswa', id),
    stats:          ()          => invoke('ppdb:stats'),
    generateNo:     ()          => invoke('ppdb:generate_no'),
  },
  pdfCetak: {
    bukuKleper:     ()                    => invoke('pdf:buku_kleper'),
    bukuIndukSiswa: (angkatan_id)         => invoke('pdf:buku_induk_siswa', angkatan_id),
    leger:          (kelas_id)            => invoke('pdf:leger', kelas_id),
    bukuIndukGuru:  ()                    => invoke('pdf:buku_induk_guru'),
    absensiGuru:    (bulan)               => invoke('pdf:absensi_guru', bulan),
    jadwal:         (kelas_id)            => invoke('pdf:jadwal', kelas_id),
    jurnal:         (kelas_id, bulan)     => invoke('pdf:jurnal', kelas_id, bulan),
    absensiSiswa:   (kelas_id, bulan)     => invoke('pdf:absensi_siswa', kelas_id, bulan),
    surat:          (params)              => invoke('pdf:surat', params),
    raportSiswa:         (periode_id, siswa_id) => invoke('pdf:raport_siswa', periode_id, siswa_id),
    raportAll:           (periode_id)            => invoke('pdf:raport_all', periode_id),
    kartuUjian:          (cfg_id, kelas_id) => invoke('pdf:kartu_ujian', cfg_id, kelas_id),
    kartuUjianPeserta:   (cfg_id)          => invoke('pdf:kartu_ujian_peserta', cfg_id),
    rekapBOS:            (tahun, sem)      => invoke('pdf:rekap_bos', tahun, sem),
  },
  leger: {
    get: kelas_id => invoke('leger:get', kelas_id),
  },
  surat: {
    getSiswa:  id  => invoke('surat:get_siswa', id),
    list:      ()  => invoke('surat:list'),
    saveLog:   d   => invoke('surat:save_log', d),
  },
  kelas: {
    list:    ()        => invoke('kelas:list'),
    get:     id        => invoke('kelas:get', id),
    add:     d         => invoke('kelas:add', d),
    update:  (id, d)   => invoke('kelas:update', id, d),
    delete:  id        => invoke('kelas:delete', id),
    siswa:   id        => invoke('kelas:siswa', id),
  },
  denah: {
    get:   kelas_id          => invoke('denah:get', kelas_id),
    save:  (kelas_id, seats) => invoke('denah:save', kelas_id, seats),
    auto:  kelas_id          => invoke('denah:auto', kelas_id),
  },
  jadwal: {
    get:   kelas_id        => invoke('jadwal:get', kelas_id),
    save:  (kelas_id, rows) => invoke('jadwal:save', kelas_id, rows),
  },
  jurnal: {
    list:   (kelas_id, bulan) => invoke('jurnal:list', kelas_id, bulan),
    add:    d                 => invoke('jurnal:add', d),
    update: (id, d)           => invoke('jurnal:update', id, d),
    delete: id                => invoke('jurnal:delete', id),
  },
  absensi: {
    get:   (kelas_id, tanggal) => invoke('absensi:get', kelas_id, tanggal),
    save:  (kelas_id, tanggal, rows) => invoke('absensi:save', kelas_id, tanggal, rows),
    rekap: (kelas_id, bulan)   => invoke('absensi:rekap', kelas_id, bulan),
  },
  db: {
    backup:  () => invoke('db:backup'),
    restore: () => invoke('db:restore'),
  },
  app: {
    getPaths:   () => invoke('app:get_paths'),
    openOutput: () => invoke('app:open_output'),
    stats:      () => invoke('stats:dashboard'),
  },
})
