name: Purge All Artifacts

on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete all artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: "0 days"
          skip-recent: 0
